// Code generated by https://github.com/go-dev-frame/sponge

package routers

import (
	"github.com/gin-gonic/gin"

	"github.com/go-dev-frame/sponge/pkg/logger"
	//"github.com/go-dev-frame/sponge/pkg/middleware"

	cloud_storageV1 "cloud-storage/api/cloud_storage/v1"
	"cloud-storage/internal/handler"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		chunkMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			chunkRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewChunkHandler())
		})
}

func chunkRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService cloud_storageV1.ChunkLogicer) {
	cloud_storageV1.RegisterChunkRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		cloud_storageV1.WithChunkLogger(logger.Get()),
		cloud_storageV1.WithChunkHTTPResponse(),
		cloud_storageV1.WithChunkErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func chunkMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/chunk/:id  will take effect
	// c.setGroupPath("/api/v1/chunk", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/file/upload/prepare", middleware.Auth())    // FileUploadPrepare 文件上传前基本信息处理
	//c.setSinglePath("POST", "/file/upload/chunk", middleware.Auth())    // FileUploadChunk 文件分片上传
	//c.setSinglePath("POST", "/file/upload/chunk/complete", middleware.Auth())    // FileUploadChunkComplete 文件分片上传完成
}
