// Code generated by https://github.com/go-dev-frame/sponge

package routers

import (
	"github.com/gin-gonic/gin"

	"github.com/go-dev-frame/sponge/pkg/logger"
	//"github.com/go-dev-frame/sponge/pkg/middleware"

	cloud_storageV1 "cloud-storage/api/cloud_storage/v1"
	"cloud-storage/internal/handler"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		shareMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			shareRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewShareHandler())
		})
}

func shareRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService cloud_storageV1.ShareLogicer) {
	cloud_storageV1.RegisterShareRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		cloud_storageV1.WithShareLogger(logger.Get()),
		cloud_storageV1.WithShareHTTPResponse(),
		cloud_storageV1.WithShareErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func shareMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/share/:id  will take effect
	// c.setGroupPath("/api/v1/share", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("GET", "/share/basic/detail", middleware.Auth())    // ShareBasicDetail 获取资源详情
	//c.setSinglePath("POST", "/share/basic/create", middleware.Auth())    // ShareBasicCreate 创建分享记录
	//c.setSinglePath("POST", "/share/basic/save", middleware.Auth())    // ShareBasicSave 资源保存
}
