// Code generated by hertz generator.

package file

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileuploadMw() []app.HandlerFunc {
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _file0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userfiledeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userfilelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userfilemoveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userfilenameupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _folderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userfoldercreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userfolderlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repositoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userrepositorysaveMw() []app.HandlerFunc {
	// your code...
	return nil
}
