// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v6.32.0
// source: chunk.proto

package chunk

import (
	_ "cloud-storage/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileUploadChunkCompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5        string       `protobuf:"bytes,1,opt,name=md5,proto3" form:"md5" json:"md5,omitempty" query:"md5"`
	Name       string       `protobuf:"bytes,2,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	Ext        string       `protobuf:"bytes,3,opt,name=ext,proto3" form:"ext" json:"ext,omitempty" query:"ext"`
	Size       int64        `protobuf:"varint,4,opt,name=size,proto3" form:"size" json:"size,omitempty" query:"size"`
	Key        string       `protobuf:"bytes,5,opt,name=key,proto3" form:"key" json:"key,omitempty" query:"key"`
	UploadId   string       `protobuf:"bytes,6,opt,name=upload_id,json=uploadId,proto3" form:"upload_id" json:"upload_id,omitempty" query:"upload_id"`
	CosObjects []*CosObject `protobuf:"bytes,7,rep,name=cos_objects,json=cosObjects,proto3" form:"cos_objects" json:"cos_objects,omitempty" query:"cos_objects"`
}

func (x *FileUploadChunkCompleteRequest) Reset() {
	*x = FileUploadChunkCompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadChunkCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadChunkCompleteRequest) ProtoMessage() {}

func (x *FileUploadChunkCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadChunkCompleteRequest.ProtoReflect.Descriptor instead.
func (*FileUploadChunkCompleteRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *FileUploadChunkCompleteRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FileUploadChunkCompleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileUploadChunkCompleteRequest) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *FileUploadChunkCompleteRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadChunkCompleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FileUploadChunkCompleteRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *FileUploadChunkCompleteRequest) GetCosObjects() []*CosObject {
	if x != nil {
		return x.CosObjects
	}
	return nil
}

type CosObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartNumber int32  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" form:"part_number" json:"part_number,omitempty" query:"part_number"`
	Etag       string `protobuf:"bytes,2,opt,name=etag,proto3" form:"etag" json:"etag,omitempty" query:"etag"`
}

func (x *CosObject) Reset() {
	*x = CosObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosObject) ProtoMessage() {}

func (x *CosObject) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosObject.ProtoReflect.Descriptor instead.
func (*CosObject) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *CosObject) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *CosObject) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type FileUploadChunkCompleteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" form:"identity" json:"identity,omitempty" query:"identity"`
}

func (x *FileUploadChunkCompleteReply) Reset() {
	*x = FileUploadChunkCompleteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadChunkCompleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadChunkCompleteReply) ProtoMessage() {}

func (x *FileUploadChunkCompleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadChunkCompleteReply.ProtoReflect.Descriptor instead.
func (*FileUploadChunkCompleteReply) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *FileUploadChunkCompleteReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type FileUploadChunkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=key,proto3" form:"key" json:"key,omitempty" query:"key"`
	UploadId   string `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" form:"upload_id" json:"upload_id,omitempty" query:"upload_id"`
	PartNumber int32  `protobuf:"varint,3,opt,name=part_number,json=partNumber,proto3" form:"part_number" json:"part_number,omitempty" query:"part_number"`
}

func (x *FileUploadChunkRequest) Reset() {
	*x = FileUploadChunkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadChunkRequest) ProtoMessage() {}

func (x *FileUploadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadChunkRequest.ProtoReflect.Descriptor instead.
func (*FileUploadChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *FileUploadChunkRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FileUploadChunkRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *FileUploadChunkRequest) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

type FileUploadChunkReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Etag string `protobuf:"bytes,1,opt,name=etag,proto3" form:"etag" json:"etag,omitempty" query:"etag"`
}

func (x *FileUploadChunkReply) Reset() {
	*x = FileUploadChunkReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadChunkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadChunkReply) ProtoMessage() {}

func (x *FileUploadChunkReply) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadChunkReply.ProtoReflect.Descriptor instead.
func (*FileUploadChunkReply) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *FileUploadChunkReply) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type FileUploadPrepareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5  string `protobuf:"bytes,1,opt,name=md5,proto3" form:"md5" json:"md5,omitempty" query:"md5"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	Ext  string `protobuf:"bytes,3,opt,name=ext,proto3" form:"ext" json:"ext,omitempty" query:"ext"`
}

func (x *FileUploadPrepareRequest) Reset() {
	*x = FileUploadPrepareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadPrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadPrepareRequest) ProtoMessage() {}

func (x *FileUploadPrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadPrepareRequest.ProtoReflect.Descriptor instead.
func (*FileUploadPrepareRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{5}
}

func (x *FileUploadPrepareRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FileUploadPrepareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileUploadPrepareRequest) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

type FileUploadPrepareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" form:"identity" json:"identity,omitempty" query:"identity"`
	UploadId string `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" form:"upload_id" json:"upload_id,omitempty" query:"upload_id"`
	Key      string `protobuf:"bytes,3,opt,name=key,proto3" form:"key" json:"key,omitempty" query:"key"`
}

func (x *FileUploadPrepareReply) Reset() {
	*x = FileUploadPrepareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadPrepareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadPrepareReply) ProtoMessage() {}

func (x *FileUploadPrepareReply) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadPrepareReply.ProtoReflect.Descriptor instead.
func (*FileUploadPrepareReply) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *FileUploadPrepareReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *FileUploadPrepareReply) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *FileUploadPrepareReply) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_chunk_proto protoreflect.FileDescriptor

var file_chunk_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xce, 0x01, 0x0a, 0x1e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x31, 0x0a,
	0x0b, 0x63, 0x6f, 0x73, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x43, 0x6f, 0x73, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x0a, 0x63, 0x6f, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x22, 0x40, 0x0a, 0x09, 0x43, 0x6f, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x65, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x74,
	0x61, 0x67, 0x22, 0x3a, 0x0a, 0x1c, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x68,
	0x0a, 0x16, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61,
	0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x65, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x65, 0x74, 0x61, 0x67, 0x22, 0x52, 0x0a, 0x18, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x22, 0x63, 0x0a, 0x16, 0x46, 0x69, 0x6c, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0xe6, 0x02,
	0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x6d, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x1f, 0x2e, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0xd2, 0xc1,
	0x18, 0x14, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x70,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x65, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1d, 0x2e, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0xd2, 0xc1, 0x18, 0x12, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x86, 0x01,
	0x0a, 0x17, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0xd2, 0xc1, 0x18, 0x1b, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2f, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chunk_proto_rawDescOnce sync.Once
	file_chunk_proto_rawDescData = file_chunk_proto_rawDesc
)

func file_chunk_proto_rawDescGZIP() []byte {
	file_chunk_proto_rawDescOnce.Do(func() {
		file_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(file_chunk_proto_rawDescData)
	})
	return file_chunk_proto_rawDescData
}

var file_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chunk_proto_goTypes = []interface{}{
	(*FileUploadChunkCompleteRequest)(nil), // 0: chunk.FileUploadChunkCompleteRequest
	(*CosObject)(nil),                      // 1: chunk.CosObject
	(*FileUploadChunkCompleteReply)(nil),   // 2: chunk.FileUploadChunkCompleteReply
	(*FileUploadChunkRequest)(nil),         // 3: chunk.FileUploadChunkRequest
	(*FileUploadChunkReply)(nil),           // 4: chunk.FileUploadChunkReply
	(*FileUploadPrepareRequest)(nil),       // 5: chunk.FileUploadPrepareRequest
	(*FileUploadPrepareReply)(nil),         // 6: chunk.FileUploadPrepareReply
}
var file_chunk_proto_depIdxs = []int32{
	1, // 0: chunk.FileUploadChunkCompleteRequest.cos_objects:type_name -> chunk.CosObject
	5, // 1: chunk.chunk.FileUploadPrepare:input_type -> chunk.FileUploadPrepareRequest
	3, // 2: chunk.chunk.FileUploadChunk:input_type -> chunk.FileUploadChunkRequest
	0, // 3: chunk.chunk.FileUploadChunkComplete:input_type -> chunk.FileUploadChunkCompleteRequest
	6, // 4: chunk.chunk.FileUploadPrepare:output_type -> chunk.FileUploadPrepareReply
	4, // 5: chunk.chunk.FileUploadChunk:output_type -> chunk.FileUploadChunkReply
	2, // 6: chunk.chunk.FileUploadChunkComplete:output_type -> chunk.FileUploadChunkCompleteReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chunk_proto_init() }
func file_chunk_proto_init() {
	if File_chunk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chunk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadChunkCompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chunk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chunk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadChunkCompleteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chunk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadChunkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chunk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadChunkReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chunk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadPrepareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chunk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadPrepareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chunk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chunk_proto_goTypes,
		DependencyIndexes: file_chunk_proto_depIdxs,
		MessageInfos:      file_chunk_proto_msgTypes,
	}.Build()
	File_chunk_proto = out.File
	file_chunk_proto_rawDesc = nil
	file_chunk_proto_goTypes = nil
	file_chunk_proto_depIdxs = nil
}
