// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v6.32.0
// source: share.proto

package share

import (
	_ "cloud-storage/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareBasicSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepositoryIdentity string `protobuf:"bytes,1,opt,name=repository_identity,json=repositoryIdentity,proto3" form:"repository_identity" json:"repository_identity,omitempty" query:"repository_identity"`
	ParentId           int64  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" form:"parent_id" json:"parent_id,omitempty" query:"parent_id"`
}

func (x *ShareBasicSaveRequest) Reset() {
	*x = ShareBasicSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicSaveRequest) ProtoMessage() {}

func (x *ShareBasicSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicSaveRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicSaveRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{0}
}

func (x *ShareBasicSaveRequest) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *ShareBasicSaveRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ShareBasicSaveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" form:"identity" json:"identity,omitempty" query:"identity"`
}

func (x *ShareBasicSaveReply) Reset() {
	*x = ShareBasicSaveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicSaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicSaveReply) ProtoMessage() {}

func (x *ShareBasicSaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicSaveReply.ProtoReflect.Descriptor instead.
func (*ShareBasicSaveReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{1}
}

func (x *ShareBasicSaveReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ShareBasicDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" form:"identity" json:"identity,omitempty" query:"identity"`
}

func (x *ShareBasicDetailRequest) Reset() {
	*x = ShareBasicDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicDetailRequest) ProtoMessage() {}

func (x *ShareBasicDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicDetailRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicDetailRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{2}
}

func (x *ShareBasicDetailRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ShareBasicDetailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepositoryIdentity string `protobuf:"bytes,1,opt,name=repository_identity,json=repositoryIdentity,proto3" form:"repository_identity" json:"repository_identity,omitempty" query:"repository_identity"`
	Name               string `protobuf:"bytes,2,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	Ext                string `protobuf:"bytes,3,opt,name=ext,proto3" form:"ext" json:"ext,omitempty" query:"ext"`
	Size               int64  `protobuf:"varint,4,opt,name=size,proto3" form:"size" json:"size,omitempty" query:"size"`
	Path               string `protobuf:"bytes,5,opt,name=path,proto3" form:"path" json:"path,omitempty" query:"path"`
}

func (x *ShareBasicDetailReply) Reset() {
	*x = ShareBasicDetailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicDetailReply) ProtoMessage() {}

func (x *ShareBasicDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicDetailReply.ProtoReflect.Descriptor instead.
func (*ShareBasicDetailReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{3}
}

func (x *ShareBasicDetailReply) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *ShareBasicDetailReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShareBasicDetailReply) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ShareBasicDetailReply) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShareBasicDetailReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ShareBasicCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserRepositoryIdentity string `protobuf:"bytes,1,opt,name=user_repository_identity,json=userRepositoryIdentity,proto3" form:"user_repository_identity" json:"user_repository_identity,omitempty" query:"user_repository_identity"`
	ExpiredTime            int32  `protobuf:"varint,2,opt,name=expired_time,json=expiredTime,proto3" form:"expired_time" json:"expired_time,omitempty" query:"expired_time"`
}

func (x *ShareBasicCreateRequest) Reset() {
	*x = ShareBasicCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicCreateRequest) ProtoMessage() {}

func (x *ShareBasicCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicCreateRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicCreateRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{4}
}

func (x *ShareBasicCreateRequest) GetUserRepositoryIdentity() string {
	if x != nil {
		return x.UserRepositoryIdentity
	}
	return ""
}

func (x *ShareBasicCreateRequest) GetExpiredTime() int32 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

type ShareBasicCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" form:"identity" json:"identity,omitempty" query:"identity"`
}

func (x *ShareBasicCreateReply) Reset() {
	*x = ShareBasicCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicCreateReply) ProtoMessage() {}

func (x *ShareBasicCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicCreateReply.ProtoReflect.Descriptor instead.
func (*ShareBasicCreateReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{5}
}

func (x *ShareBasicCreateReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

var File_share_proto protoreflect.FileDescriptor

var file_share_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x65, 0x0a, 0x15, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x13, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x35, 0x0a, 0x17, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x22, 0x96, 0x01, 0x0a, 0x15, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x76, 0x0a, 0x17, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x18, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x33, 0x0a, 0x15, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x32, 0xc0, 0x02, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x12, 0x69, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x17, 0xca, 0xc1, 0x18, 0x13, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x69, 0x0a, 0x10, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x1e, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0xd2,
	0xc1, 0x18, 0x13, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x61, 0x0a, 0x0e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76, 0x65, 0x12, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x15, 0xd2, 0xc1, 0x18, 0x11, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2f, 0x73, 0x61, 0x76, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_share_proto_rawDescOnce sync.Once
	file_share_proto_rawDescData = file_share_proto_rawDesc
)

func file_share_proto_rawDescGZIP() []byte {
	file_share_proto_rawDescOnce.Do(func() {
		file_share_proto_rawDescData = protoimpl.X.CompressGZIP(file_share_proto_rawDescData)
	})
	return file_share_proto_rawDescData
}

var file_share_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_share_proto_goTypes = []interface{}{
	(*ShareBasicSaveRequest)(nil),   // 0: share.ShareBasicSaveRequest
	(*ShareBasicSaveReply)(nil),     // 1: share.ShareBasicSaveReply
	(*ShareBasicDetailRequest)(nil), // 2: share.ShareBasicDetailRequest
	(*ShareBasicDetailReply)(nil),   // 3: share.ShareBasicDetailReply
	(*ShareBasicCreateRequest)(nil), // 4: share.ShareBasicCreateRequest
	(*ShareBasicCreateReply)(nil),   // 5: share.ShareBasicCreateReply
}
var file_share_proto_depIdxs = []int32{
	2, // 0: share.share.ShareBasicDetail:input_type -> share.ShareBasicDetailRequest
	4, // 1: share.share.ShareBasicCreate:input_type -> share.ShareBasicCreateRequest
	0, // 2: share.share.ShareBasicSave:input_type -> share.ShareBasicSaveRequest
	3, // 3: share.share.ShareBasicDetail:output_type -> share.ShareBasicDetailReply
	5, // 4: share.share.ShareBasicCreate:output_type -> share.ShareBasicCreateReply
	1, // 5: share.share.ShareBasicSave:output_type -> share.ShareBasicSaveReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_share_proto_init() }
func file_share_proto_init() {
	if File_share_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_share_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicSaveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicDetailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_share_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_share_proto_goTypes,
		DependencyIndexes: file_share_proto_depIdxs,
		MessageInfos:      file_share_proto_msgTypes,
	}.Build()
	File_share_proto = out.File
	file_share_proto_rawDesc = nil
	file_share_proto_goTypes = nil
	file_share_proto_depIdxs = nil
}
