// Code generated by hertz generator.

package chunk

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chunkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileuploadchunkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileuploadchunkcompleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileuploadprepareMw() []app.HandlerFunc {
	// your code...
	return nil
}
