// Code generated by hertz generator.

package share

import (
	"context"

	share "cloud-storage/biz/model/share"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ShareBasicDetail .
// @router /share/basic/detail [GET]
func ShareBasicDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.ShareBasicDetailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.ShareBasicDetailReply)

	c.JSON(consts.StatusOK, resp)
}

// ShareBasicCreate .
// @router /share/basic/create [POST]
func ShareBasicCreate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.ShareBasicCreateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.ShareBasicCreateReply)

	c.JSON(consts.StatusOK, resp)
}

// ShareBasicSave .
// @router /share/basic/save [POST]
func ShareBasicSave(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.ShareBasicSaveRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.ShareBasicSaveReply)

	c.JSON(consts.StatusOK, resp)
}
