// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// chunk business-level http error codes.
// the chunkNO value range is 1~999, if the same error code is used, it will cause panic.
var (
	chunkNO       = 1
	chunkName     = "chunk"
	chunkBaseCode = errcode.HCode(chunkNO)

	ErrFileUploadPrepareChunk       = errcode.NewError(chunkBaseCode+1, "failed to FileUploadPrepare "+chunkName)
	ErrFileUploadChunkChunk         = errcode.NewError(chunkBaseCode+2, "failed to FileUploadChunk "+chunkName)
	ErrFileUploadChunkCompleteChunk = errcode.NewError(chunkBaseCode+3, "failed to FileUploadChunkComplete "+chunkName)

	// error codes are globally unique, adding 1 to the previous error code
)
