// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// file business-level http error codes.
// the fileNO value range is 1~999, if the same error code is used, it will cause panic.
var (
	fileNO       = 2
	fileName     = "file"
	fileBaseCode = errcode.HCode(fileNO)

	ErrFileUploadFile         = errcode.NewError(fileBaseCode+1, "failed to FileUpload "+fileName)
	ErrUserRepositorySaveFile = errcode.NewError(fileBaseCode+2, "failed to UserRepositorySave "+fileName)
	ErrUserFileListFile       = errcode.NewError(fileBaseCode+3, "failed to UserFileList "+fileName)
	ErrUserFolderListFile     = errcode.NewError(fileBaseCode+4, "failed to UserFolderList "+fileName)
	ErrUserFileNameUpdateFile = errcode.NewError(fileBaseCode+5, "failed to UserFileNameUpdate "+fileName)
	ErrUserFolderCreateFile   = errcode.NewError(fileBaseCode+6, "failed to UserFolderCreate "+fileName)
	ErrUserFileDeleteFile     = errcode.NewError(fileBaseCode+7, "failed to UserFileDelete "+fileName)
	ErrUserFileMoveFile       = errcode.NewError(fileBaseCode+8, "failed to UserFileMove "+fileName)

	// error codes are globally unique, adding 1 to the previous error code
)
