// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserBasic = "user_basic"

// UserBasic mapped from table <user_basic>
type UserBasic struct {
	ID        uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Identity  *string        `gorm:"column:identity;type:varchar(36)" json:"identity"`
	Name      *string        `gorm:"column:name;type:varchar(60)" json:"name"`
	Password  *string        `gorm:"column:password;type:varchar(32)" json:"password"`
	Email     *string        `gorm:"column:email;type:varchar(100)" json:"email"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName UserBasic's table name
func (*UserBasic) TableName() string {
	return TableNameUserBasic
}
