// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserRepository = "user_repository"

// UserRepository mapped from table <user_repository>
type UserRepository struct {
	ID                 uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Identity           string         `gorm:"column:identity;type:varchar(36)" json:"identity"`
	UserIdentity       string         `gorm:"column:user_identity;type:varchar(36)" json:"user_identity"`
	ParentID           int32          `gorm:"column:parent_id;type:int" json:"parent_id"`
	RepositoryIdentity string         `gorm:"column:repository_identity;type:varchar(36)" json:"repository_identity"`
	Ext                string         `gorm:"column:ext;type:varchar(255);comment:文件或文件夹类型" json:"ext"` // 文件或文件夹类型
	Name               string         `gorm:"column:name;type:varchar(255)" json:"name"`
	CreatedAt          time.Time      `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName UserRepository's table name
func (*UserRepository) TableName() string {
	return TableNameUserRepository
}
