// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	RepositoryPool *repositoryPool
	ShareBasic     *shareBasic
	UserBasic      *userBasic
	UserRepository *userRepository
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	RepositoryPool = &Q.RepositoryPool
	ShareBasic = &Q.ShareBasic
	UserBasic = &Q.UserBasic
	UserRepository = &Q.UserRepository
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		RepositoryPool: newRepositoryPool(db, opts...),
		ShareBasic:     newShareBasic(db, opts...),
		UserBasic:      newUserBasic(db, opts...),
		UserRepository: newUserRepository(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	RepositoryPool repositoryPool
	ShareBasic     shareBasic
	UserBasic      userBasic
	UserRepository userRepository
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		RepositoryPool: q.RepositoryPool.clone(db),
		ShareBasic:     q.ShareBasic.clone(db),
		UserBasic:      q.UserBasic.clone(db),
		UserRepository: q.UserRepository.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		RepositoryPool: q.RepositoryPool.replaceDB(db),
		ShareBasic:     q.ShareBasic.replaceDB(db),
		UserBasic:      q.UserBasic.replaceDB(db),
		UserRepository: q.UserRepository.replaceDB(db),
	}
}

type queryCtx struct {
	RepositoryPool IRepositoryPoolDo
	ShareBasic     IShareBasicDo
	UserBasic      IUserBasicDo
	UserRepository IUserRepositoryDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		RepositoryPool: q.RepositoryPool.WithContext(ctx),
		ShareBasic:     q.ShareBasic.WithContext(ctx),
		UserBasic:      q.UserBasic.WithContext(ctx),
		UserRepository: q.UserRepository.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
