// Code generated by hertz generator.

package share

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shareMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sharebasiccreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sharebasicdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sharebasicsaveMw() []app.HandlerFunc {
	// your code...
	return nil
}
