// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: api/cloud_storage/v1/file.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFileMoveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identity       string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	ParentIdentity string                 `protobuf:"bytes,2,opt,name=parent_identity,json=parentIdentity,proto3" json:"parent_identity"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserFileMoveRequest) Reset() {
	*x = UserFileMoveRequest{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileMoveRequest) ProtoMessage() {}

func (x *UserFileMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileMoveRequest.ProtoReflect.Descriptor instead.
func (*UserFileMoveRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *UserFileMoveRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UserFileMoveRequest) GetParentIdentity() string {
	if x != nil {
		return x.ParentIdentity
	}
	return ""
}

type UserFileMoveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileMoveReply) Reset() {
	*x = UserFileMoveReply{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileMoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileMoveReply) ProtoMessage() {}

func (x *UserFileMoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileMoveReply.ProtoReflect.Descriptor instead.
func (*UserFileMoveReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{1}
}

type UserFileDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileDeleteRequest) Reset() {
	*x = UserFileDeleteRequest{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileDeleteRequest) ProtoMessage() {}

func (x *UserFileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserFileDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *UserFileDeleteRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type UserFileDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileDeleteReply) Reset() {
	*x = UserFileDeleteReply{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileDeleteReply) ProtoMessage() {}

func (x *UserFileDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileDeleteReply.ProtoReflect.Descriptor instead.
func (*UserFileDeleteReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{3}
}

type UserFolderCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFolderCreateRequest) Reset() {
	*x = UserFolderCreateRequest{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFolderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFolderCreateRequest) ProtoMessage() {}

func (x *UserFolderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFolderCreateRequest.ProtoReflect.Descriptor instead.
func (*UserFolderCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{4}
}

func (x *UserFolderCreateRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UserFolderCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserFolderCreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFolderCreateReply) Reset() {
	*x = UserFolderCreateReply{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFolderCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFolderCreateReply) ProtoMessage() {}

func (x *UserFolderCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFolderCreateReply.ProtoReflect.Descriptor instead.
func (*UserFolderCreateReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{5}
}

func (x *UserFolderCreateReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type UserFileNameUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileNameUpdateRequest) Reset() {
	*x = UserFileNameUpdateRequest{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileNameUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileNameUpdateRequest) ProtoMessage() {}

func (x *UserFileNameUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileNameUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserFileNameUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{6}
}

func (x *UserFileNameUpdateRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UserFileNameUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserFileNameUpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileNameUpdateReply) Reset() {
	*x = UserFileNameUpdateReply{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileNameUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileNameUpdateReply) ProtoMessage() {}

func (x *UserFileNameUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileNameUpdateReply.ProtoReflect.Descriptor instead.
func (*UserFileNameUpdateReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{7}
}

type UserFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileListRequest) Reset() {
	*x = UserFileListRequest{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileListRequest) ProtoMessage() {}

func (x *UserFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileListRequest.ProtoReflect.Descriptor instead.
func (*UserFileListRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{8}
}

func (x *UserFileListRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UserFileListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserFileListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UserFileListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserFile            `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileListReply) Reset() {
	*x = UserFileListReply{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileListReply) ProtoMessage() {}

func (x *UserFileListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileListReply.ProtoReflect.Descriptor instead.
func (*UserFileListReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{9}
}

func (x *UserFileListReply) GetList() []*UserFile {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *UserFileListReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UserFile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Identity           string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity"`
	RepositoryIdentity string                 `protobuf:"bytes,3,opt,name=repository_identity,json=repositoryIdentity,proto3" json:"repository_identity"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Ext                string                 `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext"`
	Path               string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path"`
	Size               int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserFile) Reset() {
	*x = UserFile{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFile) ProtoMessage() {}

func (x *UserFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFile.ProtoReflect.Descriptor instead.
func (*UserFile) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{10}
}

func (x *UserFile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserFile) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UserFile) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *UserFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserFile) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *UserFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UserFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UserFolderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFolderListRequest) Reset() {
	*x = UserFolderListRequest{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFolderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFolderListRequest) ProtoMessage() {}

func (x *UserFolderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFolderListRequest.ProtoReflect.Descriptor instead.
func (*UserFolderListRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{11}
}

func (x *UserFolderListRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type UserFolderListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserFolder          `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFolderListReply) Reset() {
	*x = UserFolderListReply{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFolderListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFolderListReply) ProtoMessage() {}

func (x *UserFolderListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFolderListReply.ProtoReflect.Descriptor instead.
func (*UserFolderListReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{12}
}

func (x *UserFolderListReply) GetList() []*UserFolder {
	if x != nil {
		return x.List
	}
	return nil
}

type UserFolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFolder) Reset() {
	*x = UserFolder{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFolder) ProtoMessage() {}

func (x *UserFolder) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFolder.ProtoReflect.Descriptor instead.
func (*UserFolder) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{13}
}

func (x *UserFolder) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UserFolder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserRepositorySaveRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ParentId           int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id"`
	RepositoryIdentity string                 `protobuf:"bytes,2,opt,name=repository_identity,json=repositoryIdentity,proto3" json:"repository_identity"`
	Ext                string                 `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserRepositorySaveRequest) Reset() {
	*x = UserRepositorySaveRequest{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRepositorySaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRepositorySaveRequest) ProtoMessage() {}

func (x *UserRepositorySaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRepositorySaveRequest.ProtoReflect.Descriptor instead.
func (*UserRepositorySaveRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{14}
}

func (x *UserRepositorySaveRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UserRepositorySaveRequest) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *UserRepositorySaveRequest) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *UserRepositorySaveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserRepositorySaveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRepositorySaveReply) Reset() {
	*x = UserRepositorySaveReply{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRepositorySaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRepositorySaveReply) ProtoMessage() {}

func (x *UserRepositorySaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRepositorySaveReply.ProtoReflect.Descriptor instead.
func (*UserRepositorySaveReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{15}
}

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Ext           string                 `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{16}
}

func (x *FileUploadRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileUploadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileUploadRequest) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *FileUploadRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileUploadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	Ext           string                 `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadReply) Reset() {
	*x = FileUploadReply{}
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadReply) ProtoMessage() {}

func (x *FileUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadReply.ProtoReflect.Descriptor instead.
func (*FileUploadReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_file_proto_rawDescGZIP(), []int{17}
}

func (x *FileUploadReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *FileUploadReply) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *FileUploadReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_cloud_storage_v1_file_proto protoreflect.FileDescriptor

const file_api_cloud_storage_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/cloud_storage/v1/file.proto\x1a\x1cgoogle/api/annotations.proto\"Z\n" +
	"\x13UserFileMoveRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12'\n" +
	"\x0fparent_identity\x18\x02 \x01(\tR\x0eparentIdentity\"\x13\n" +
	"\x11UserFileMoveReply\"3\n" +
	"\x15UserFileDeleteRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\x15\n" +
	"\x13UserFileDeleteReply\"J\n" +
	"\x17UserFolderCreateRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\x15UserFolderCreateReply\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"K\n" +
	"\x19UserFileNameUpdateRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x19\n" +
	"\x17UserFileNameUpdateReply\"Y\n" +
	"\x13UserFileListRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"H\n" +
	"\x11UserFileListReply\x12\x1d\n" +
	"\x04list\x18\x01 \x03(\v2\t.UserFileR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xb5\x01\n" +
	"\bUserFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12/\n" +
	"\x13repository_identity\x18\x03 \x01(\tR\x12repositoryIdentity\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\x05 \x01(\tR\x03ext\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\"3\n" +
	"\x15UserFolderListRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"6\n" +
	"\x13UserFolderListReply\x12\x1f\n" +
	"\x04list\x18\x01 \x03(\v2\v.UserFolderR\x04list\"<\n" +
	"\n" +
	"UserFolder\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x19UserRepositorySaveRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x03R\bparentId\x12/\n" +
	"\x13repository_identity\x18\x02 \x01(\tR\x12repositoryIdentity\x12\x10\n" +
	"\x03ext\x18\x03 \x01(\tR\x03ext\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x19\n" +
	"\x17UserRepositorySaveReply\"u\n" +
	"\x11FileUploadRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\x03 \x01(\tR\x03ext\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"S\n" +
	"\x0fFileUploadReply\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x10\n" +
	"\x03ext\x18\x02 \x01(\tR\x03ext\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name2\x91\x06\n" +
	"\x04file\x12V\n" +
	"\n" +
	"FileUpload\x12\x12.FileUploadRequest\x1a\x10.FileUploadReply\"\"\x82\xd3\xe4\x93\x02\x1c\n" +
	"\t[no_bind]:\x01*\"\f/file/upload\x12w\n" +
	"\x12UserRepositorySave\x12\x1a.UserRepositorySaveRequest\x1a\x18.UserRepositorySaveReply\"+\x82\xd3\xe4\x93\x02%\n" +
	"\t[no_bind]:\x01*\"\x15/user/repository/save\x12T\n" +
	"\fUserFileList\x12\x14.UserFileListRequest\x1a\x12.UserFileListReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/user/file/list\x12\\\n" +
	"\x0eUserFolderList\x12\x16.UserFolderListRequest\x1a\x14.UserFolderListReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/user/folder/list\x12m\n" +
	"\x12UserFileNameUpdate\x12\x1a.UserFileNameUpdateRequest\x1a\x18.UserFileNameUpdateReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/user/file/name/update\x12d\n" +
	"\x10UserFolderCreate\x12\x18.UserFolderCreateRequest\x1a\x16.UserFolderCreateReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/user/folder/create\x12Y\n" +
	"\x0eUserFileDelete\x12\x16.UserFileDeleteRequest\x1a\x14.UserFileDeleteReply\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/user/file/delete\x12T\n" +
	"\fUserFileMove\x12\x14.UserFileMoveRequest\x1a\x12.UserFileMoveReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/user/file/moveB'Z%cloud-storage/api/cloud_storage/v1;v1b\x06proto3"

var (
	file_api_cloud_storage_v1_file_proto_rawDescOnce sync.Once
	file_api_cloud_storage_v1_file_proto_rawDescData []byte
)

func file_api_cloud_storage_v1_file_proto_rawDescGZIP() []byte {
	file_api_cloud_storage_v1_file_proto_rawDescOnce.Do(func() {
		file_api_cloud_storage_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cloud_storage_v1_file_proto_rawDesc), len(file_api_cloud_storage_v1_file_proto_rawDesc)))
	})
	return file_api_cloud_storage_v1_file_proto_rawDescData
}

var file_api_cloud_storage_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_cloud_storage_v1_file_proto_goTypes = []any{
	(*UserFileMoveRequest)(nil),       // 0: UserFileMoveRequest
	(*UserFileMoveReply)(nil),         // 1: UserFileMoveReply
	(*UserFileDeleteRequest)(nil),     // 2: UserFileDeleteRequest
	(*UserFileDeleteReply)(nil),       // 3: UserFileDeleteReply
	(*UserFolderCreateRequest)(nil),   // 4: UserFolderCreateRequest
	(*UserFolderCreateReply)(nil),     // 5: UserFolderCreateReply
	(*UserFileNameUpdateRequest)(nil), // 6: UserFileNameUpdateRequest
	(*UserFileNameUpdateReply)(nil),   // 7: UserFileNameUpdateReply
	(*UserFileListRequest)(nil),       // 8: UserFileListRequest
	(*UserFileListReply)(nil),         // 9: UserFileListReply
	(*UserFile)(nil),                  // 10: UserFile
	(*UserFolderListRequest)(nil),     // 11: UserFolderListRequest
	(*UserFolderListReply)(nil),       // 12: UserFolderListReply
	(*UserFolder)(nil),                // 13: UserFolder
	(*UserRepositorySaveRequest)(nil), // 14: UserRepositorySaveRequest
	(*UserRepositorySaveReply)(nil),   // 15: UserRepositorySaveReply
	(*FileUploadRequest)(nil),         // 16: FileUploadRequest
	(*FileUploadReply)(nil),           // 17: FileUploadReply
}
var file_api_cloud_storage_v1_file_proto_depIdxs = []int32{
	10, // 0: UserFileListReply.list:type_name -> UserFile
	13, // 1: UserFolderListReply.list:type_name -> UserFolder
	16, // 2: file.FileUpload:input_type -> FileUploadRequest
	14, // 3: file.UserRepositorySave:input_type -> UserRepositorySaveRequest
	8,  // 4: file.UserFileList:input_type -> UserFileListRequest
	11, // 5: file.UserFolderList:input_type -> UserFolderListRequest
	6,  // 6: file.UserFileNameUpdate:input_type -> UserFileNameUpdateRequest
	4,  // 7: file.UserFolderCreate:input_type -> UserFolderCreateRequest
	2,  // 8: file.UserFileDelete:input_type -> UserFileDeleteRequest
	0,  // 9: file.UserFileMove:input_type -> UserFileMoveRequest
	17, // 10: file.FileUpload:output_type -> FileUploadReply
	15, // 11: file.UserRepositorySave:output_type -> UserRepositorySaveReply
	9,  // 12: file.UserFileList:output_type -> UserFileListReply
	12, // 13: file.UserFolderList:output_type -> UserFolderListReply
	7,  // 14: file.UserFileNameUpdate:output_type -> UserFileNameUpdateReply
	5,  // 15: file.UserFolderCreate:output_type -> UserFolderCreateReply
	3,  // 16: file.UserFileDelete:output_type -> UserFileDeleteReply
	1,  // 17: file.UserFileMove:output_type -> UserFileMoveReply
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_cloud_storage_v1_file_proto_init() }
func file_api_cloud_storage_v1_file_proto_init() {
	if File_api_cloud_storage_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cloud_storage_v1_file_proto_rawDesc), len(file_api_cloud_storage_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cloud_storage_v1_file_proto_goTypes,
		DependencyIndexes: file_api_cloud_storage_v1_file_proto_depIdxs,
		MessageInfos:      file_api_cloud_storage_v1_file_proto_msgTypes,
	}.Build()
	File_api_cloud_storage_v1_file_proto = out.File
	file_api_cloud_storage_v1_file_proto_goTypes = nil
	file_api_cloud_storage_v1_file_proto_depIdxs = nil
}
