// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: api/cloud_storage/v1/share.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareBasicSaveRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RepositoryIdentity string                 `protobuf:"bytes,1,opt,name=repository_identity,json=repositoryIdentity,proto3" json:"repository_identity"`
	ParentId           int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ShareBasicSaveRequest) Reset() {
	*x = ShareBasicSaveRequest{}
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareBasicSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicSaveRequest) ProtoMessage() {}

func (x *ShareBasicSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicSaveRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicSaveRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_share_proto_rawDescGZIP(), []int{0}
}

func (x *ShareBasicSaveRequest) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *ShareBasicSaveRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ShareBasicSaveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareBasicSaveReply) Reset() {
	*x = ShareBasicSaveReply{}
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareBasicSaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicSaveReply) ProtoMessage() {}

func (x *ShareBasicSaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicSaveReply.ProtoReflect.Descriptor instead.
func (*ShareBasicSaveReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_share_proto_rawDescGZIP(), []int{1}
}

func (x *ShareBasicSaveReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ShareBasicDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareBasicDetailRequest) Reset() {
	*x = ShareBasicDetailRequest{}
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareBasicDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicDetailRequest) ProtoMessage() {}

func (x *ShareBasicDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicDetailRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_share_proto_rawDescGZIP(), []int{2}
}

func (x *ShareBasicDetailRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ShareBasicDetailReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RepositoryIdentity string                 `protobuf:"bytes,1,opt,name=repository_identity,json=repositoryIdentity,proto3" json:"repository_identity"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Ext                string                 `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext"`
	Size               int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size"`
	Path               string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ShareBasicDetailReply) Reset() {
	*x = ShareBasicDetailReply{}
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareBasicDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicDetailReply) ProtoMessage() {}

func (x *ShareBasicDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicDetailReply.ProtoReflect.Descriptor instead.
func (*ShareBasicDetailReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_share_proto_rawDescGZIP(), []int{3}
}

func (x *ShareBasicDetailReply) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *ShareBasicDetailReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShareBasicDetailReply) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ShareBasicDetailReply) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShareBasicDetailReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ShareBasicCreateRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserRepositoryIdentity string                 `protobuf:"bytes,1,opt,name=user_repository_identity,json=userRepositoryIdentity,proto3" json:"user_repository_identity"`
	ExpiredTime            int32                  `protobuf:"varint,2,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ShareBasicCreateRequest) Reset() {
	*x = ShareBasicCreateRequest{}
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareBasicCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicCreateRequest) ProtoMessage() {}

func (x *ShareBasicCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicCreateRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_share_proto_rawDescGZIP(), []int{4}
}

func (x *ShareBasicCreateRequest) GetUserRepositoryIdentity() string {
	if x != nil {
		return x.UserRepositoryIdentity
	}
	return ""
}

func (x *ShareBasicCreateRequest) GetExpiredTime() int32 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

type ShareBasicCreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareBasicCreateReply) Reset() {
	*x = ShareBasicCreateReply{}
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareBasicCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicCreateReply) ProtoMessage() {}

func (x *ShareBasicCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_share_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicCreateReply.ProtoReflect.Descriptor instead.
func (*ShareBasicCreateReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_share_proto_rawDescGZIP(), []int{5}
}

func (x *ShareBasicCreateReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

var File_api_cloud_storage_v1_share_proto protoreflect.FileDescriptor

const file_api_cloud_storage_v1_share_proto_rawDesc = "" +
	"\n" +
	" api/cloud_storage/v1/share.proto\x1a\x1cgoogle/api/annotations.proto\"e\n" +
	"\x15ShareBasicSaveRequest\x12/\n" +
	"\x13repository_identity\x18\x01 \x01(\tR\x12repositoryIdentity\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\"1\n" +
	"\x13ShareBasicSaveReply\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"5\n" +
	"\x17ShareBasicDetailRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\x96\x01\n" +
	"\x15ShareBasicDetailReply\x12/\n" +
	"\x13repository_identity\x18\x01 \x01(\tR\x12repositoryIdentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\x03 \x01(\tR\x03ext\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"v\n" +
	"\x17ShareBasicCreateRequest\x128\n" +
	"\x18user_repository_identity\x18\x01 \x01(\tR\x16userRepositoryIdentity\x12!\n" +
	"\fexpired_time\x18\x02 \x01(\x05R\vexpiredTime\"3\n" +
	"\x15ShareBasicCreateReply\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity2\xae\x02\n" +
	"\x05share\x12a\n" +
	"\x10ShareBasicDetail\x12\x18.ShareBasicDetailRequest\x1a\x16.ShareBasicDetailReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/share/basic/detail\x12d\n" +
	"\x10ShareBasicCreate\x12\x18.ShareBasicCreateRequest\x1a\x16.ShareBasicCreateReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/share/basic/create\x12\\\n" +
	"\x0eShareBasicSave\x12\x16.ShareBasicSaveRequest\x1a\x14.ShareBasicSaveReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/share/basic/saveB'Z%cloud-storage/api/cloud_storage/v1;v1b\x06proto3"

var (
	file_api_cloud_storage_v1_share_proto_rawDescOnce sync.Once
	file_api_cloud_storage_v1_share_proto_rawDescData []byte
)

func file_api_cloud_storage_v1_share_proto_rawDescGZIP() []byte {
	file_api_cloud_storage_v1_share_proto_rawDescOnce.Do(func() {
		file_api_cloud_storage_v1_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cloud_storage_v1_share_proto_rawDesc), len(file_api_cloud_storage_v1_share_proto_rawDesc)))
	})
	return file_api_cloud_storage_v1_share_proto_rawDescData
}

var file_api_cloud_storage_v1_share_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_cloud_storage_v1_share_proto_goTypes = []any{
	(*ShareBasicSaveRequest)(nil),   // 0: ShareBasicSaveRequest
	(*ShareBasicSaveReply)(nil),     // 1: ShareBasicSaveReply
	(*ShareBasicDetailRequest)(nil), // 2: ShareBasicDetailRequest
	(*ShareBasicDetailReply)(nil),   // 3: ShareBasicDetailReply
	(*ShareBasicCreateRequest)(nil), // 4: ShareBasicCreateRequest
	(*ShareBasicCreateReply)(nil),   // 5: ShareBasicCreateReply
}
var file_api_cloud_storage_v1_share_proto_depIdxs = []int32{
	2, // 0: share.ShareBasicDetail:input_type -> ShareBasicDetailRequest
	4, // 1: share.ShareBasicCreate:input_type -> ShareBasicCreateRequest
	0, // 2: share.ShareBasicSave:input_type -> ShareBasicSaveRequest
	3, // 3: share.ShareBasicDetail:output_type -> ShareBasicDetailReply
	5, // 4: share.ShareBasicCreate:output_type -> ShareBasicCreateReply
	1, // 5: share.ShareBasicSave:output_type -> ShareBasicSaveReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_cloud_storage_v1_share_proto_init() }
func file_api_cloud_storage_v1_share_proto_init() {
	if File_api_cloud_storage_v1_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cloud_storage_v1_share_proto_rawDesc), len(file_api_cloud_storage_v1_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cloud_storage_v1_share_proto_goTypes,
		DependencyIndexes: file_api_cloud_storage_v1_share_proto_depIdxs,
		MessageInfos:      file_api_cloud_storage_v1_share_proto_msgTypes,
	}.Build()
	File_api_cloud_storage_v1_share_proto = out.File
	file_api_cloud_storage_v1_share_proto_goTypes = nil
	file_api_cloud_storage_v1_share_proto_depIdxs = nil
}
