// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: api/cloud_storage/v1/user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthorizationRequest) Reset() {
	*x = RefreshAuthorizationRequest{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthorizationRequest) ProtoMessage() {}

func (x *RefreshAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*RefreshAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{0}
}

type RefreshAuthorizationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthorizationReply) Reset() {
	*x = RefreshAuthorizationReply{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthorizationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthorizationReply) ProtoMessage() {}

func (x *RefreshAuthorizationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthorizationReply.ProtoReflect.Descriptor instead.
func (*RefreshAuthorizationReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshAuthorizationReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshAuthorizationReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterRequest) Reset() {
	*x = UserRegisterRequest{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterRequest) ProtoMessage() {}

func (x *UserRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterRequest.ProtoReflect.Descriptor instead.
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegisterRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UserRegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterReply) Reset() {
	*x = UserRegisterReply{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterReply) ProtoMessage() {}

func (x *UserRegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterReply.ProtoReflect.Descriptor instead.
func (*UserRegisterReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{3}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailRequest) Reset() {
	*x = UserDetailRequest{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailRequest) ProtoMessage() {}

func (x *UserDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailRequest.ProtoReflect.Descriptor instead.
func (*UserDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserDetailRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type UserDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailReply) Reset() {
	*x = UserDetailReply{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailReply) ProtoMessage() {}

func (x *UserDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailReply.ProtoReflect.Descriptor instead.
func (*UserDetailReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserDetailReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDetailReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MailCodeSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailCodeSendRequest) Reset() {
	*x = MailCodeSendRequest{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailCodeSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailCodeSendRequest) ProtoMessage() {}

func (x *MailCodeSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailCodeSendRequest.ProtoReflect.Descriptor instead.
func (*MailCodeSendRequest) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *MailCodeSendRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MailCodeSendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailCodeSendReply) Reset() {
	*x = MailCodeSendReply{}
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailCodeSendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailCodeSendReply) ProtoMessage() {}

func (x *MailCodeSendReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cloud_storage_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailCodeSendReply.ProtoReflect.Descriptor instead.
func (*MailCodeSendReply) Descriptor() ([]byte, []int) {
	return file_api_cloud_storage_v1_user_proto_rawDescGZIP(), []int{9}
}

var File_api_cloud_storage_v1_user_proto protoreflect.FileDescriptor

const file_api_cloud_storage_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/cloud_storage/v1/user.proto\x1a\x1cgoogle/api/annotations.proto\"\x1d\n" +
	"\x1bRefreshAuthorizationRequest\"V\n" +
	"\x19RefreshAuthorizationReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"o\n" +
	"\x13UserRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"\x13\n" +
	"\x11UserRegisterReply\">\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"G\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"/\n" +
	"\x11UserDetailRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\";\n" +
	"\x0fUserDetailReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"+\n" +
	"\x13MailCodeSendRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x13\n" +
	"\x11MailCodeSendReply2\xc5\x03\n" +
	"\x04user\x12?\n" +
	"\tUserLogin\x12\r.LoginRequest\x1a\v.LoginReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/login\x12K\n" +
	"\n" +
	"UserDetail\x12\x12.UserDetailRequest\x1a\x10.UserDetailReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/user/detail\x12e\n" +
	"\x14MailCodeSendRegister\x12\x14.MailCodeSendRequest\x1a\x12.MailCodeSendReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/mail/code/send/register\x12S\n" +
	"\fUserRegister\x12\x14.UserRegisterRequest\x1a\x12.UserRegisterReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/user/register\x12s\n" +
	"\x14RefreshAuthorization\x12\x1c.RefreshAuthorizationRequest\x1a\x1a.RefreshAuthorizationReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/refresh/authorizationB'Z%cloud-storage/api/cloud_storage/v1;v1b\x06proto3"

var (
	file_api_cloud_storage_v1_user_proto_rawDescOnce sync.Once
	file_api_cloud_storage_v1_user_proto_rawDescData []byte
)

func file_api_cloud_storage_v1_user_proto_rawDescGZIP() []byte {
	file_api_cloud_storage_v1_user_proto_rawDescOnce.Do(func() {
		file_api_cloud_storage_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cloud_storage_v1_user_proto_rawDesc), len(file_api_cloud_storage_v1_user_proto_rawDesc)))
	})
	return file_api_cloud_storage_v1_user_proto_rawDescData
}

var file_api_cloud_storage_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_cloud_storage_v1_user_proto_goTypes = []any{
	(*RefreshAuthorizationRequest)(nil), // 0: RefreshAuthorizationRequest
	(*RefreshAuthorizationReply)(nil),   // 1: RefreshAuthorizationReply
	(*UserRegisterRequest)(nil),         // 2: UserRegisterRequest
	(*UserRegisterReply)(nil),           // 3: UserRegisterReply
	(*LoginRequest)(nil),                // 4: LoginRequest
	(*LoginReply)(nil),                  // 5: LoginReply
	(*UserDetailRequest)(nil),           // 6: UserDetailRequest
	(*UserDetailReply)(nil),             // 7: UserDetailReply
	(*MailCodeSendRequest)(nil),         // 8: MailCodeSendRequest
	(*MailCodeSendReply)(nil),           // 9: MailCodeSendReply
}
var file_api_cloud_storage_v1_user_proto_depIdxs = []int32{
	4, // 0: user.UserLogin:input_type -> LoginRequest
	6, // 1: user.UserDetail:input_type -> UserDetailRequest
	8, // 2: user.MailCodeSendRegister:input_type -> MailCodeSendRequest
	2, // 3: user.UserRegister:input_type -> UserRegisterRequest
	0, // 4: user.RefreshAuthorization:input_type -> RefreshAuthorizationRequest
	5, // 5: user.UserLogin:output_type -> LoginReply
	7, // 6: user.UserDetail:output_type -> UserDetailReply
	9, // 7: user.MailCodeSendRegister:output_type -> MailCodeSendReply
	3, // 8: user.UserRegister:output_type -> UserRegisterReply
	1, // 9: user.RefreshAuthorization:output_type -> RefreshAuthorizationReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_cloud_storage_v1_user_proto_init() }
func file_api_cloud_storage_v1_user_proto_init() {
	if File_api_cloud_storage_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cloud_storage_v1_user_proto_rawDesc), len(file_api_cloud_storage_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cloud_storage_v1_user_proto_goTypes,
		DependencyIndexes: file_api_cloud_storage_v1_user_proto_depIdxs,
		MessageInfos:      file_api_cloud_storage_v1_user_proto_msgTypes,
	}.Build()
	File_api_cloud_storage_v1_user_proto = out.File
	file_api_cloud_storage_v1_user_proto_goTypes = nil
	file_api_cloud_storage_v1_user_proto_depIdxs = nil
}
